### ISSUE TITLE
Can't run with llama model

### ISSUE THREAD

**Issue by nrosen1** [evandez/relations#25]
[demo.ipynb](https://github.com/evandez/relations/blob/main/demo/demo.ipynb) fails to run with model="llama" since model "meta-llama/Llama-2-13b-chat-hf" is not in DOWNLOADABLE_MODELS.

**Comment by arnab-api** [comment]
Hi, 
we didn't try with any of the chat models. But, if you want to work with new models try adding them to the `DOWNLOADABLE_MODELS` [here](https://github.com/evandez/relations/blob/main/src/models.py#L32).
Or, download `hf` version of your model and put it in the default `models` directory. Change [this](https://github.com/evandez/relations/blob/main/src/utils/env_utils.py#L13) variable to where you store the models.
